- name: Create temporary chezmoi source directory
  ansible.builtin.tempfile:
    state: directory
    suffix: chezmoi-source
  register: temporary_chezmoi_source

- name: Create temporary script directory
  ansible.builtin.tempfile:
    state: directory
    suffix: dotfiles-scripts
  register: temporary_dotfiles_scripts

- name: Apply dotfiles with temporary chezmoi source
  block:
    - name: Show temporary chezmoi source directory
      ansible.builtin.debug:
        msg: "temporary chezmoi source: {{ temporary_chezmoi_source.path }}"

    - name: Copy build chezmoi source script
      ansible.builtin.copy:
        src: build-chezmoi-source.sh
        dest: "{{ temporary_dotfiles_scripts.path }}/build-chezmoi-source.sh"
        mode: "0755"

    - name: Build temporary chezmoi source
      ansible.builtin.command:
        cmd: >-
          {{ temporary_dotfiles_scripts.path }}/build-chezmoi-source.sh
          {{ playbook_dir }}/../dotfiles
          {{ temporary_chezmoi_source.path }}

    - name: Show generated chezmoi source files
      ansible.builtin.command:
        cmd: find "{{ temporary_chezmoi_source.path }}" -type f -print
      register: generated_chezmoi_source_files
      changed_when: false

    - name: Display generated chezmoi source files
      ansible.builtin.debug:
        msg: "{{ generated_chezmoi_source_files.stdout_lines }}"

    - name: Show chezmoi diff
      ansible.builtin.command:
        cmd: chezmoi diff --source "{{ temporary_chezmoi_source.path }}"
      register: chezmoi_diff
      changed_when: false
      failed_when: false

    - name: Display chezmoi diff
      ansible.builtin.debug:
        msg: "{{ chezmoi_diff.stdout_lines }}"
      when: chezmoi_diff.stdout != ""

    - name: Show no chezmoi diff
      ansible.builtin.debug:
        msg: "No chezmoi diff."
      when: chezmoi_diff.stdout == ""

    - name: Apply chezmoi source
      ansible.builtin.command:
        cmd: chezmoi apply --source "{{ temporary_chezmoi_source.path }}" --verbose
      register: chezmoi_apply
      changed_when: chezmoi_apply.stdout != ""
      failed_when: chezmoi_apply.rc != 0

    - name: Display chezmoi apply output
      ansible.builtin.debug:
        msg: "{{ chezmoi_apply.stdout_lines }}"
      when: chezmoi_apply.stdout != ""

  always:
    - name: Remove temporary chezmoi source directory
      ansible.builtin.file:
        path: "{{ temporary_chezmoi_source.path }}"
        state: absent

    - name: Remove temporary script directory
      ansible.builtin.file:
        path: "{{ temporary_dotfiles_scripts.path }}"
        state: absent
