- name: Check act command
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/act"
  register: act_command

- name: Install act
  when: not act_command.stat.exists
  block:
    - name: Ensure local bin directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Download act installer
      ansible.builtin.get_url:
        url: "{{ act_install_url }}"
        dest: /tmp/act-installer.sh
        mode: "0755"

    - name: Run act installer
      ansible.builtin.command:
        cmd: >-
          /bin/sh /tmp/act-installer.sh
          -b {{ ansible_env.HOME }}/.local/bin

  always:
    - name: Remove act installer
      ansible.builtin.file:
        path: /tmp/act-installer.sh
        state: absent

- name: Check act command after installation
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.local/bin/act --version"
  register: act_command_after_install
  changed_when: false

- name: Show act command status after installation
  ansible.builtin.debug:
    msg:
      - "act is installed: {{ act_command_after_install.rc == 0 }}"
      - "act version: {{ act_command_after_install.stdout }}"
